"""added order

Revision ID: 6a43ebdd6b19
Revises: 6a1222d392f1
Create Date: 2023-07-26 13:24:43.347001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a43ebdd6b19'
down_revision = '6a1222d392f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
