"""added rewards

Revision ID: aea530fdc5fc
Revises: 25d3a531436a
Create Date: 2023-07-28 13:31:03.716608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea530fdc5fc'
down_revision = '25d3a531436a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('custom_code', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reward')
    # ### end Alembic commands ###
